# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 383f6e5e08c74be28094c6a79e4004649d63fea1a52304642c6686d33cb89ca098739433c48e6ed41dd636f96e3cd952e65652440fcde75371a6c816e815a7b0

test:
  secret_key_base: aff644b44bd108a39cdcb038ae52b59b3a6fedb3470f0ee51f1955f6f7fb890ff14f71be240c990c41cb557abc2d1170c0e21cd8b5b7dcadadc1cb2aa7311b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
